# vim: se expandtab ts=4 sw=2 ai
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
    solution: '**/*.slnx'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: github.com_amoldeshpande_somehow_different
    repositoryName: $(Build.Repository.Name)
    tagSource: 'userSpecifiedTag'
    tag: $(Build.BuildNumber)
    title: $(Build.BuildId) Release From $(Build.SourceBranchName)
    assets: $(System.DefaultWorkingDirectory)/bin/Release/*
